server:
  port: 10011
spring:
  application:
    name: market-zuul
zuul:
  prefix: /api
  routes:
    contact-service: /contact/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
    registry-fetch-interval-seconds: 10
    fetch-registry: true
    register-with-eureka: true
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 40000
